name: Index Pipeline
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - main
    paths:
      - 'packages/index-pipeline/**'
      - 'packages/eslint-config/**'
      - '.github/workflows/index-pipeline.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/index-pipeline/**'
      - 'packages/eslint-config/**'
      - '.github/workflows/index-pipeline.yml'
      - 'pnpm-lock.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 18
          - 20
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm -r --filter @hash-stream/index-pipeline run lint
      - run: pnpm -r --filter @hash-stream/index-pipeline run attw
      - run: pnpm -r --filter @hash-stream/index-pipeline test
        env:
          AWS_REGION: 'us-west-2'
          AWS_ACCESS_KEY_ID: 'NOSUCH'
          AWS_SECRET_ACCESS_KEY: 'NOSUCH'
