name: Publish to npm

on:
  release:
    types: [created]
  workflow_dispatch: # allows manual trigger from UI

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Debug release tag and context
        run: |
          echo "Release context: ${{ toJson(github.event) }}"
          echo "Release tag name: ${{ github.event.release.tag_name }}"

      - name: Extract released package name from tag
        id: tag
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          echo "Release tag: $TAG_NAME"

          # Using regular expression to extract package name
          if [[ "$TAG_NAME" =~ ^([a-zA-Z0-9_-]+)-v[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
            PKG_NAME="${BASH_REMATCH[1]}"
            echo "Package name: $PKG_NAME"
            echo "name=$PKG_NAME" >> $GITHUB_OUTPUT
          else
            echo "❌ Could not extract package name from tag: $TAG_NAME"
            exit 1
          fi

      - name: Publish only released package
        run: |
          pnpm --filter "${{ steps.tag.outputs.name }}" publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
